services:
  backend:
    build:
      context: .
      dockerfile: CursoOnline.WebAPI/Dockerfile
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__MongoDB: "mongodb+srv://usuario:senha@seubanco.mongodb.net"

  frontend:
    build:
      context: .
      dockerfile: FrontEndReact/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
